name: Tom Savage
title: Tom Savage
author: Tom Savage
description: "My Blog"
#github: [metadata]
#remote_theme: niklasbuschmann/contrast

# Page settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/
hide_title: false            # remove site heading in the header
post_footer: true            # show previous and next links at the end of each post

# Theme settings
show_footer: false
dark_theme: false            # use the dark mode as default
dark_header: false           # keep the header dark
# style: minimal             # use a simpler style inspired by the minima theme

navigation:                  # (optional) site navigation in the header
  - index.html
#  - title: "https://"       # linking external sites is also supported

icons:                       # (optional) icons in the header, see http://fontawesome.com/icons
  github: "https://github.com/tcsavage"
  rss: "/feed.xml"

# Pagination
show_excerpts: false         # preview articles on the home page
paginate: 8                  # number of articles per page
excerpt_separator: "\n\n\n"  # indicate the end of the excerpt by two blank lines

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-default-layout
#  - jekyll-remote-theme
