version: '3.4'
services:
  jekyll:
    image: jekyll/jekyll:pages
    command: jekyll serve --watch --incremental --drafts
    ports:
        - 4000:4000
    environment:
        JEKYLL_GITHUB_TOKEN: "${JEKYLL_GITHUB_TOKEN}"
    volumes:
        - .:/srv/jekyll
